"""
Train a small ReLU-only plausibility classifier that distinguishes real
preprocessed TinyTaxiNet images from synthetic "fake" images that mimic the
kinds of non-physical inputs Marabou produces under the per-pixel box.

Architecture:
  128 -> 64 -> 16 -> 1   (ReLU on hidden, linear output = logit)

Negative (fake) examples are generated by four methods, mixed evenly:
  (1) Per-pixel-box corners: each pixel independently set to its min or max
      from the training distribution. Simulates Marabou's "corner of the box"
      witnesses.
  (2) Cross-image blends: pixels sampled uniformly at random from different
      real images, destroying spatial correlation.
  (3) Uniform noise: pixel values drawn from U(0, 1). Baseline "obviously fake."
  (4) High-frequency patterns: checkerboards and salt-and-pepper on a real base.

The classifier is small and ReLU-only so it can optionally be composed with
other Marabou queries later as an in-query plausibility filter.
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import json
import numpy as np
import h5py

SEED = 42
np.random.seed(SEED)
import tensorflow as tf
tf.random.set_seed(SEED)
tf.keras.utils.set_random_seed(SEED)

from tensorflow import keras
from tensorflow.keras import layers

DATA_PATH = "VerifyGAN/data/SK_DownsampledGANFocusAreaData.h5"
WEIGHTS_PATH = "plausibility_classifier.npz"
METRICS_PATH = "plausibility_classifier_metrics.json"
ONNX_PATH = "plausibility_classifier.onnx"

NUM_PIXELS = 128
HIDDEN_1 = 64
HIDDEN_2 = 16
EPOCHS = 100
BATCH_SIZE = 128
LR = 1e-3


def load_real_images():
    with h5py.File(DATA_PATH, "r") as f:
        images = f["y_train"][:].reshape(-1, NUM_PIXELS).astype(np.float32)
    return images


def make_fakes(real_images, n_per_type, rng):
    """Generate four types of synthetic fakes, n_per_type of each."""
    fakes = []
    pixel_min = real_images.min(axis=0)
    pixel_max = real_images.max(axis=0)

    # Type 1: Per-pixel-box corners
    corners = np.zeros((n_per_type, NUM_PIXELS), dtype=np.float32)
    for i in range(n_per_type):
        pick_high = rng.random(NUM_PIXELS) > 0.5
        corners[i] = np.where(pick_high, pixel_max, pixel_min)
    fakes.append(corners)

    # Type 2: Cross-image blends (each pixel independently sampled from a random real image)
    blends = np.zeros((n_per_type, NUM_PIXELS), dtype=np.float32)
    for i in range(n_per_type):
        # For each pixel, pick a random real image and use its value for that pixel
        img_indices = rng.integers(0, len(real_images), NUM_PIXELS)
        blends[i] = real_images[img_indices, np.arange(NUM_PIXELS)]
    fakes.append(blends)

    # Type 3: Uniform noise in data range
    noise_min = float(pixel_min.min())
    noise_max = float(pixel_max.max())
    uniform = rng.uniform(noise_min, noise_max, (n_per_type, NUM_PIXELS)).astype(np.float32)
    fakes.append(uniform)

    # Type 4: High-frequency patterns on real base (salt-and-pepper + checkerboard)
    hf = np.zeros((n_per_type, NUM_PIXELS), dtype=np.float32)
    for i in range(n_per_type):
        base = real_images[rng.integers(0, len(real_images))].copy()
        if rng.random() < 0.5:
            # Salt-and-pepper: flip ~30% of pixels to min or max
            mask = rng.random(NUM_PIXELS) < 0.3
            flip = rng.random(NUM_PIXELS) > 0.5
            base[mask] = np.where(flip[mask], pixel_max[mask], pixel_min[mask])
        else:
            # Checkerboard addition
            checkerboard = ((np.arange(NUM_PIXELS) // 16 + np.arange(NUM_PIXELS) % 16) % 2) * 0.3
            base = np.clip(base + checkerboard - 0.15, 0, 1)
        hf[i] = base
    fakes.append(hf)

    return np.concatenate(fakes, axis=0), [
        ("box_corners", n_per_type),
        ("cross_blends", n_per_type),
        ("uniform_noise", n_per_type),
        ("high_freq_patterns", n_per_type),
    ]


def build_classifier():
    inp = keras.Input(shape=(NUM_PIXELS,), name="pixels_in")
    h = layers.Dense(HIDDEN_1, activation="relu", name="c1")(inp)
    h = layers.Dense(HIDDEN_2, activation="relu", name="c2")(h)
    logit = layers.Dense(1, activation="linear", name="score")(h)
    return keras.Model(inp, logit, name="plausibility_classifier")


def main():
    rng = np.random.default_rng(SEED)
    print("Loading real images...")
    real = load_real_images()
    n_real = len(real)
    print(f"  {n_real} real images")

    n_per_type = n_real // 4    # balance: total fakes == total reals
    print(f"Generating fakes ({n_per_type} per type, 4 types)...")
    fake, fake_composition = make_fakes(real, n_per_type, rng)
    print(f"  {len(fake)} total fake images")

    # Build dataset
    x = np.concatenate([real, fake], axis=0)
    y = np.concatenate([np.ones(n_real), np.zeros(len(fake))]).astype(np.float32)

    # Shuffle
    perm = rng.permutation(len(x))
    x = x[perm]
    y = y[perm]

    # 90/10 train/val split
    n_val = int(0.1 * len(x))
    x_val, x_train = x[:n_val], x[n_val:]
    y_val, y_train = y[:n_val], y[n_val:]

    # Build and compile
    print("\nBuilding classifier...")
    clf = build_classifier()
    clf.compile(
        optimizer=keras.optimizers.Adam(LR),
        loss=keras.losses.BinaryCrossentropy(from_logits=True),
        metrics=[keras.metrics.BinaryAccuracy(threshold=0.0)],
    )
    clf.summary()

    print("\nTraining...")
    history = clf.fit(
        x_train, y_train,
        validation_data=(x_val, y_val),
        epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=2,
    )

    # Score distributions
    real_logits = clf.predict(real, verbose=0).flatten()
    fake_logits = clf.predict(fake, verbose=0).flatten()
    real_probs = 1.0 / (1.0 + np.exp(-real_logits))
    fake_probs = 1.0 / (1.0 + np.exp(-fake_logits))

    print("\nScore distributions:")
    print(f"  Real logit  mean/std/min/max: {real_logits.mean():.3f} / {real_logits.std():.3f} / {real_logits.min():.3f} / {real_logits.max():.3f}")
    print(f"  Fake logit  mean/std/min/max: {fake_logits.mean():.3f} / {fake_logits.std():.3f} / {fake_logits.min():.3f} / {fake_logits.max():.3f}")
    print(f"  Real prob   mean: {real_probs.mean():.3f}  (fraction > 0.5: {(real_probs > 0.5).mean():.3f})")
    print(f"  Fake prob   mean: {fake_probs.mean():.3f}  (fraction < 0.5: {(fake_probs < 0.5).mean():.3f})")

    # Save weights (numpy arrays)
    saved = {"seed": SEED}
    for name in ["c1", "c2", "score"]:
        layer = clf.get_layer(name)
        W, b = layer.get_weights()
        saved[f"{name}_W"] = W.astype(np.float64)
        saved[f"{name}_b"] = b.astype(np.float64)
    np.savez(WEIGHTS_PATH, **saved)
    print(f"\nSaved weights: {WEIGHTS_PATH}")

    # ONNX export for later in-query use
    import tf2onnx
    spec = (tf.TensorSpec((None, NUM_PIXELS), tf.float32, name="pixels_in"),)
    tf2onnx.convert.from_keras(clf, input_signature=spec, opset=13, output_path=ONNX_PATH)
    print(f"Saved ONNX: {ONNX_PATH}")

    metrics = {
        "seed": SEED,
        "architecture": f"{NUM_PIXELS} -> {HIDDEN_1} -> {HIDDEN_2} -> 1",
        "epochs": EPOCHS,
        "n_real_train": int(n_real),
        "n_fake_train": int(len(fake)),
        "fake_composition": [{"type": t, "count": int(n)} for t, n in fake_composition],
        "final_train_loss": float(history.history["loss"][-1]),
        "final_val_loss": float(history.history["val_loss"][-1]),
        "final_train_acc": float(history.history["binary_accuracy"][-1]),
        "final_val_acc": float(history.history["val_binary_accuracy"][-1]),
        "real_logit_stats": {"mean": float(real_logits.mean()), "std": float(real_logits.std()),
                              "min": float(real_logits.min()), "max": float(real_logits.max())},
        "fake_logit_stats": {"mean": float(fake_logits.mean()), "std": float(fake_logits.std()),
                              "min": float(fake_logits.min()), "max": float(fake_logits.max())},
        "real_frac_above_0": float((real_probs > 0.5).mean()),
        "fake_frac_below_0": float((fake_probs < 0.5).mean()),
    }
    with open(METRICS_PATH, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"Saved metrics: {METRICS_PATH}")


if __name__ == "__main__":
    main()
